#!/usr/bin/env sh

if [ -z "${MANTA_KEY_CONTENT}" ]; then
  >&2 echo "MANTA_KEY_CONTENT must be set"
  exit 1
fi

if [ -z "${MANTA_KEY_ID}" ]; then
  >&2 echo "MANTA_KEY_ID must be set"
  exit 1
fi

if [ -z "${MANTA_URL}" ]; then
  >&2 echo "MANTA_URL must be set"
  exit 1
fi

if [ -z "${MANTA_USER}" ]; then
  >&2 echo "MANTA_USER must be set"
  exit 1
fi

if [ -z "${AWS_ACCESS_KEY_ID}" ]; then
  >&2 echo "AWS_ACCESS_KEY_ID must be set"
  exit 1
fi

if [ -z "${AWS_SECRET_ACCESS_KEY}" ]; then
  >&2 echo "AWS_SECRET_ACCESS_KEY must be set"
  exit 1
fi

echo "Copying private key to app home"
mkdir -p /home/app/.ssh
echo "${MANTA_KEY_CONTENT}" > /home/app/.ssh/id_rsa

echo "Setting process limit variables"
# The output of proclimit is very conservative, so we increase it by 4
if [ -d "/native" ]; then
    export PROC_LIMIT="`echo 4 $(/usr/local/bin/proclimit.sh) + p | dc`"
else
    export PROC_LIMIT="$(grep -c ^processor /proc/cpuinfo 2>/dev/null || 1)"
fi

# Explicitly set Nginx worker processes based on process limit setting
sed -i "s/worker_processes [[:digit:]]\+;/worker_processes $PROC_LIMIT;/" /etc/nginx/nginx.conf

# Explicitly set the number of node instances to the process limit setting
sed -i "s/instances: [[:digit:]]\+/instances: $PROC_LIMIT/" /home/app/process.yml

# Copy and configure TLS certificates
/usr/local/bin/load_tls_env.sh

# Unset potentially sensitive environment variables
unset MANTA_KEY_CONTENT
unset TLS_CERT
unset TLS_CERT_KEY

sv_stop() {
    for s in $(ls -d /etc/service/*)
    do
        /sbin/sv stop $s
    done
}

trap "sv_stop; exit" SIGTERM
/sbin/runsvdir /etc/service &
wait

# Run the init system
exec /usr/local/bin/runsvinit runsvdir -P /etc/service/
